# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{steam-condenser}
  s.version = "0.9.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Sebastian Staudt"]
  s.date = %q{2009-09-16}
  s.description = %q{A multi-language library for querying the Steam Community, Source, GoldSrc servers and Steam master servers}
  s.email = %q{koraktor@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.md"
  ]
  s.files = [
    "LICENSE",
     "README.md",
     "Rakefile",
     "VERSION.yml",
     "lib/abstract_class.rb",
     "lib/byte_buffer.rb",
     "lib/datagram_channel.rb",
     "lib/exceptions/buffer_underflow_exception.rb",
     "lib/exceptions/packet_format_exception.rb",
     "lib/exceptions/rcon_ban_exception.rb",
     "lib/exceptions/rcon_no_auth_exception.rb",
     "lib/exceptions/steam_condenser_exception.rb",
     "lib/exceptions/timeout_exception.rb",
     "lib/socket_channel.rb",
     "lib/steam-condenser.rb",
     "lib/steam/community/cacheable.rb",
     "lib/steam/community/defense_grid/defense_grid_stats.rb",
     "lib/steam/community/dods/dods_class.rb",
     "lib/steam/community/dods/dods_stats.rb",
     "lib/steam/community/dods/dods_weapon.rb",
     "lib/steam/community/game_achievement.rb",
     "lib/steam/community/game_class.rb",
     "lib/steam/community/game_stats.rb",
     "lib/steam/community/game_weapon.rb",
     "lib/steam/community/l4d/l4d_explosive.rb",
     "lib/steam/community/l4d/l4d_map.rb",
     "lib/steam/community/l4d/l4d_stats.rb",
     "lib/steam/community/l4d/l4d_weapon.rb",
     "lib/steam/community/steam_group.rb",
     "lib/steam/community/steam_id.rb",
     "lib/steam/community/tf2/tf2_class.rb",
     "lib/steam/community/tf2/tf2_class_factory.rb",
     "lib/steam/community/tf2/tf2_engineer.rb",
     "lib/steam/community/tf2/tf2_medic.rb",
     "lib/steam/community/tf2/tf2_sniper.rb",
     "lib/steam/community/tf2/tf2_spy.rb",
     "lib/steam/community/tf2/tf2_stats.rb",
     "lib/steam/packets/a2a_ack_packet.rb",
     "lib/steam/packets/a2a_ping_packet.rb",
     "lib/steam/packets/a2m_get_servers_batch2_packet.rb",
     "lib/steam/packets/a2s_info_packet.rb",
     "lib/steam/packets/a2s_player_packet.rb",
     "lib/steam/packets/a2s_rules_packet.rb",
     "lib/steam/packets/a2s_serverquery_getchallenge_packet.rb",
     "lib/steam/packets/m2a_server_batch_packet.rb",
     "lib/steam/packets/rcon/rcon_auth_request.rb",
     "lib/steam/packets/rcon/rcon_auth_response.rb",
     "lib/steam/packets/rcon/rcon_exec_request.rb",
     "lib/steam/packets/rcon/rcon_exec_response.rb",
     "lib/steam/packets/rcon/rcon_goldsrc_request.rb",
     "lib/steam/packets/rcon/rcon_goldsrc_response.rb",
     "lib/steam/packets/rcon/rcon_packet.rb",
     "lib/steam/packets/rcon/rcon_packet_factory.rb",
     "lib/steam/packets/request_with_challenge.rb",
     "lib/steam/packets/s2a_info2_packet.rb",
     "lib/steam/packets/s2a_info_base_packet.rb",
     "lib/steam/packets/s2a_info_detailed_packet.rb",
     "lib/steam/packets/s2a_player_packet.rb",
     "lib/steam/packets/s2a_rules_packet.rb",
     "lib/steam/packets/s2c_challenge_packet.rb",
     "lib/steam/packets/steam_packet.rb",
     "lib/steam/packets/steam_packet_factory.rb",
     "lib/steam/servers/game_server.rb",
     "lib/steam/servers/goldsrc_server.rb",
     "lib/steam/servers/master_server.rb",
     "lib/steam/servers/source_server.rb",
     "lib/steam/sockets/goldsrc_socket.rb",
     "lib/steam/sockets/master_server_socket.rb",
     "lib/steam/sockets/rcon_socket.rb",
     "lib/steam/sockets/source_socket.rb",
     "lib/steam/sockets/steam_socket.rb",
     "lib/steam/steam_player.rb",
     "test/byte_buffer_tests.rb",
     "test/datagram_channel_tests.rb",
     "test/query_tests.rb",
     "test/rcon_tests.rb",
     "test/socket_channel_tests.rb",
     "test/steam/communtiy/steam_community_test_suite.rb",
     "test/steam/communtiy/steam_group_tests.rb",
     "test/steam/communtiy/steam_id_tests.rb",
     "test/steam_community_tests.rb"
  ]
  s.homepage = %q{http://koraktor.github.com/steam-condenser}
  s.rdoc_options = ["--all", "--inline-source", "--line-numbers", "--charset=utf-8", "--webcvs=http://github.com/koraktor/steam-condenser/source/blob/master/ruby/%s"]
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{steam-condenser}
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Steam Condenser - A Steam query library}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<hpricot>, [">= 0.6"])
    else
      s.add_dependency(%q<hpricot>, [">= 0.6"])
    end
  else
    s.add_dependency(%q<hpricot>, [">= 0.6"])
  end
end
